### ISSUE TITLE
更好方式解决 unocss.config.ts 配置报错，防止幽灵依赖

### ISSUE THREAD

**Issue by iTsingchen** [iTsingchen/nice#17]
针对于
```
export default defineConfig({
  presets: [presetUno()],
});
```
提示
> 如果没有引用 ".pnpm/@unocss+core@0.55.7/node_modules/@unocss/core"，则无法命名 "default" 的推断类型。这很可能不可移植。需要类型注释。ts(2742)
如果没有引用 ".pnpm/@unocss+preset-mini@0.55.7/node_modules/@unocss/preset-mini/dist/shared/preset-mini.bc674518.js"，则无法命名 "default" 的推断类型。这很可能不可移植。需要类型注释。ts(2742)

 以前通过配置 `.npmrc`  来解决，但是这样容易产生**幽灵依赖**问题，需要更好的形式进行修复
```
node-linker=hoisted # https://github.com/unocss/unocss/issues/2921  https://github.com/unocss/unocss/issues/3022
```

更好的方式应该明确 config 来解决，参考：
https://github.com/microsoft/TypeScript/issues/42873
https://github.com/microsoft/TypeScript/issues/47663

**Comment by chenweiyi** [comment]
虽然不明白为什么要这么写，但是确实不报错了，感谢🙏
